#ifndef MACROS_H
#define MACROS_H 

#define BUFLEN 512
#define CLIENT_HEADER_LEN 2
#define SERVER_HEADER_LEN 1
#define MAX_PLAYERS 8
#define TICK_SECONDS 0.016
#define TICK_CLIENT_SECONDS 0.016
#define CLIENT_TIMEOUT 10
#define CLIENT_CONNECTION_RETRY_PERIOD 5

#define CLIENT_UNIT_LENGTH 66
#define CLIENT_INIT_VISIBLE_UNITS 10
#define ARENA_HALF_WIDTH_UNITS 10
#define MAX_BLOBS 16
#define INITIAL_MASS 10
#define INITIAL_SPEED_UNITS_PER_SECOND 1

#endif //MACROS_H